# Ranking Pigeons WeeWoo

## Import and Stuffs

In [1]:
import pandas as pd
import numpy as np
from numpy import array, matmul, dot, transpose
from numpy.linalg import eig, eigh, eigvals, eigvalsh
import scipy
from scipy.sparse.linalg import eigs

# Part 1

Load Table and Mingle with df

In [2]:
df = pd.read_csv(r"Matrix.csv")
page_count = int(df.size**.5)
df.set_index('page', inplace=True)
df.head(page_count + 1)

,columbidae,domestic pigeon,passenger pigeon,dodo,obsolescence,telegraph,pigeon post,vacuum tubes,flag semaphore,homing pigeon
page,,,,,,,,,,
columbidae,0,1,1,1,0.0,0.0,0.0,0.0,0.0,0.0
domestic pigeon,1,0,0,0,0.0,NaN,NaN,NaN,NaN,1.0
passenger pigeon,1,0,0,0,0.0,NaN,NaN,NaN,NaN,NaN
dodo,1,0,0,0,0.0,NaN,NaN,NaN,NaN,NaN
obsolescence,0,0,0,1,0.0,NaN,NaN,NaN,NaN,NaN
telegraph,0,0,0,0,1.0,0.0,1.0,NaN,1.0,NaN
pigeon post,0,0,0,0,NaN,1.0,0.0,NaN,NaN,1.0
vacuum tubes,0,0,0,0,1.0,NaN,NaN,0.0,NaN,NaN
flag semaphore,0,0,0,0,0.0,1.0,NaN,NaN,0.0,NaN
homing pigeon,0,1,0,0,0.0,NaN,NaN,NaN,NaN,0.0

In [3]:
df.fillna(0, inplace=True)
df = df.astype(float)
df.head(page_count + 1)

,columbidae,domestic pigeon,passenger pigeon,dodo,obsolescence,telegraph,pigeon post,vacuum tubes,flag semaphore,homing pigeon
page,,,,,,,,,,
columbidae,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
domestic pigeon,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
passenger pigeon,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
dodo,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
obsolescence,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
telegraph,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
pigeon post,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
vacuum tubes,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
flag semaphore,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
homing pigeon,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
df_test = df.copy()
df_test.head(page_count + 1)

,columbidae,domestic pigeon,passenger pigeon,dodo,obsolescence,telegraph,pigeon post,vacuum tubes,flag semaphore,homing pigeon
page,,,,,,,,,,
columbidae,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
domestic pigeon,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
passenger pigeon,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
dodo,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
obsolescence,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
telegraph,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
pigeon post,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
vacuum tubes,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
flag semaphore,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
homing pigeon,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## a) Create a column-stochastic matrix in the form of a DF

In [5]:
def colum_stoch(df_matrix):
    for i in df_matrix.columns: 
        summ = 0
        for j in df_matrix.columns:
            summ += float(df_matrix.loc[j, i])
        for k in df_matrix.columns:
            if summ == 0:
                df_matrix.loc[k,i] = 1/page_count
            else:
                df_matrix.loc[k,i] /= summ
    return df_matrix
colum_stoch(df_matrix=df_test).head(page_count + 1)

,columbidae,domestic pigeon,passenger pigeon,dodo,obsolescence,telegraph,pigeon post,vacuum tubes,flag semaphore,homing pigeon
page,,,,,,,,,,
columbidae,0.000000,0.5,1.0,0.5,0.0,0.0,0.0,0.1,0.0,0.0
domestic pigeon,0.333333,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.0,0.5
passenger pigeon,0.333333,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.0,0.0
dodo,0.333333,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.0,0.0
obsolescence,0.000000,0.0,0.0,0.5,0.0,0.0,0.0,0.1,0.0,0.0
telegraph,0.000000,0.0,0.0,0.0,0.5,0.0,1.0,0.1,1.0,0.0
pigeon post,0.000000,0.0,0.0,0.0,0.0,0.5,0.0,0.1,0.0,0.5
vacuum tubes,0.000000,0.0,0.0,0.0,0.5,0.0,0.0,0.1,0.0,0.0
flag semaphore,0.000000,0.0,0.0,0.0,0.0,0.5,0.0,0.1,0.0,0.0
homing pigeon,0.000000,0.5,0.0,0.0,0.0,0.0,0.0,0.1,0.0,0.0

## a) Go Go Matrix Rangers

P.S. Take liberty in assigning the p values to test the effects, I'll just leave it at 0.85 for generality.

In [6]:
def mat_rang(df, p):
    matrix = df.transpose().to_numpy()
    A = p * matrix + (1 - p)/page_count
    return A.transpose()
A = mat_rang(df=df_test, p= 0.85)
e_dataframe = pd.DataFrame(A)
e_dataframe.head(page_count + 1)

          0      1      2      3      4      5      6    7      8      9
0  0.015000  0.440  0.865  0.440  0.015  0.015  0.015  0.1  0.015  0.015
1  0.298333  0.015  0.015  0.015  0.015  0.015  0.015  0.1  0.015  0.440
2  0.298333  0.015  0.015  0.015  0.015  0.015  0.015  0.1  0.015  0.015
3  0.298333  0.015  0.015  0.015  0.015  0.015  0.015  0.1  0.015  0.015
4  0.015000  0.015  0.015  0.440  0.015  0.015  0.015  0.1  0.015  0.015
5  0.015000  0.015  0.015  0.015  0.440  0.015  0.865  0.1  0.865  0.015
6  0.015000  0.015  0.015  0.015  0.015  0.440  0.015  0.1  0.015  0.440
7  0.015000  0.015  0.015  0.015  0.440  0.015  0.015  0.1  0.015  0.015
8  0.015000  0.015  0.015  0.015  0.015  0.440  0.015  0.1  0.015  0.015
9  0.015000  0.440  0.015  0.015  0.015  0.015  0.015  0.1  0.015  0.015

## Get Eigenvalues and Eigenvector
Though they don't match and I had to figure out how to match them manually cuz like why wouldn't they scramble everything up

In [7]:
def near(a, b, rtol = 1e-5, atol = 1e-8):
    return np.abs(a-b)<(atol+rtol*np.abs(b))
def get_eig_1(mat_config):
    eig_val, eig_vec = eig(mat_config)
    eig_vec = eig_vec.T
    for val, vec in zip(eig_val, eig_vec):
        assert np.allclose(np.dot(mat_config, vec), val*vec)
    eig_1 = eig_vec[near(eig_val, 1.0)][0]
    return eig_1
eig_1 = get_eig_1(mat_config=A)
eig_1

array([-0.27364227, -0.17227155, -0.12217971, -0.12217971, -0.09657411,
       -0.73575113, -0.4074338 , -0.08569173, -0.35734196, -0.11786314])

## scale that bad boy up
Make sure the first norm of the vector is equal to 1.

In [8]:
def scale(v):
    summ = 0
    scaled_v = []
    for i in v:
        summ += abs(i)
    for j in v:
        scaled_v.append(j / summ)
    for k,m in enumerate(scaled_v):
        scaled_v[k] = abs(np.round(m,2))
    return scaled_v
scaled_eig_1 = scale(eig_1)
def const(v, scaled_v):
    return v[0] / scaled_v[0]
coeff = const(eig_1, scaled_eig_1)
scaled_eig_1

[0.11, 0.07, 0.05, 0.05, 0.04, 0.3, 0.16, 0.03, 0.14, 0.05]

## Rank piDgeons cuz what is life at this point

In [9]:
def ranking(scaled_v):
    dic = {}
    for i, col in enumerate(df.columns):
        dic[col] = scaled_v[i]
    return dic
dict_ranking = ranking(scaled_eig_1)
dict_ranking

{'columbidae': 0.11,
 'domestic pigeon': 0.07,
 'passenger pigeon': 0.05,
 'dodo': 0.05,
 'obsolescence': 0.04,
 'telegraph': 0.3,
 'pigeon post': 0.16,
 'vacuum tubes': 0.03,
 'flag semaphore': 0.14,
 'homing pigeon': 0.05}

# Part 2 : Mid-Max Life Crisis

In [10]:
df_opt = df.copy()

#mid-maxing - add connection form 't' to 'c', which seems to be the highest ranked page.
df_opt.loc['columbidae','telegraph'] = 1.0

#converting, scaling, comparing
def produce_ranking(df_mid_max):
    df_mid_max = colum_stoch(df_mid_max)
    A_opt = mat_rang(df=df_mid_max, p= 0.85)
    eig_opt = get_eig_1(mat_config=A_opt)
    scaled_eig_opt = scale(eig_opt)
    dict_ranking_opt = ranking(scaled_eig_opt)
    return dict_ranking_opt

# visualize data
#check = pd.DataFrame(columns = df.columns, data=A_opt)

#check if mid-maxing was successful
dict_ranking = produce_ranking(df_mid_max=df_opt)
dict_ranking

{'columbidae': 0.22,
 'domestic pigeon': 0.11,
 'passenger pigeon': 0.08,
 'dodo': 0.08,
 'obsolescence': 0.05,
 'telegraph': 0.18,
 'pigeon post': 0.1,
 'vacuum tubes': 0.04,
 'flag semaphore': 0.07,
 'homing pigeon': 0.06}

## Write algorithm to find the optimal connected system by changing exactly one entry
Did it woohooo

In [11]:
all = {}
all[('orig','orig')] = 0.11

def iterate_like_hell(df):
    df_change = df.copy()
    cols = df.columns
    for i in cols:
        for j in cols:
            if i is j:
                continue
            if df.loc[i,j] == 0:
                df_change.loc[i,j] = 1
            else:
                df_change.loc[i,j] = 0
            dict_ranking = produce_ranking(df_mid_max=df_change)
            all[(j,i)] = dict_ranking['columbidae']
            df_change.loc[i,j] = df.loc[i,j]
    return dict_ranking

dict_ranking = iterate_like_hell(df=df)
def extract(dic):
    c={}
    for key,value in dic.items():
        if 'columbidae' in key:
            c[key] = value
    return c
c = extract(dic=all)
opt_from,opt_to = max(c,key=c.get)

In [1]:
print(f'The optimal option to change is to add a connection from {opt_from} to {opt_to}.') #test

NameError: name 'opt_from' is not defined